name = input("Введите ваше имя: ")
surname = input("Введите вашу фмилию: ")
year_of_birth = int(input( "Введите год рождения: "))
city_of_residence = input("Введите город проживания: ")
your_hobby = input("Введите ваше хобби: ")
pet = input("у вас есть питомец есть/нету: ")
favorite_color = input("Введите ваш любимый цвет: ")
age = 2022 - year_of_birth
print(" ")
print("Обрабатывается информация...")
print("Имя: " + name)
print("Фамилия: " + surname)
print("Возраст: " + str (age))
print("город: " + city_of_residence)
print("Хобби: " + your_hobby)
print("Наличие питомца: " + pet)
print("Любимый цвет: " + favorite_color)
